qiime2/q2-sample-classifier

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/utilities.py

fixes #33 
fixes #29 
fixes #26 
fixes #24 
fixes #22

fixes to help docs, default params, and _load_data

---

q2_sample_classifier/utilities.py

removed index from feature importance tables

---

q2_sample_classifier/utilities.py

Depends on https://github.com/qiime2/q2templates/pull/25

MAINT: update to use `q2templates.df_to_html`

---

q2_sample_classifier/assets/index.html

ENH: added collapse widget to feature importance viz results

---

README.md

Dropped readme tutorials

---

q2_sample_classifier/assets/index.html
q2_sample_classifier/classify.py
q2_sample_classifier/utilities.py

BUG: Fixed HTML title

---

q2_sample_classifier/tests/test_classifier.py

This is how I'm going to get that hacktoberfest t-shirt!

MAINT: update testing API to use validate

---

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/data/false-coordinates.tsv
q2_sample_classifier/tests/test_classifier.py

``predict_coordinates`` was an experimental method and has pretty much dropped off my radar. If I plan to reinstate it in the future, I may place it instead in q2-coordinates.

CLEANUP: removed predict_coordinates and coordinates format

---

q2_sample_classifier/assets/index.html
q2_sample_classifier/utilities.py

added download button for accuracy results

---

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/utilities.py
q2_sample_classifier/visuals.py

See qiime2/qiime2#359 for details.

MAINT: new Metadata updates

---

q2_sample_classifier/citations.bib
q2_sample_classifier/plugin_setup.py
setup.py

ENH: added citations

---

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/utilities.py

predict! and fixed issue with sparse arrays of importance

---

q2_sample_classifier/assets/index.html
q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/utilities.py
q2_sample_classifier/visuals.py

fixes #107 
does not produce all plots listed in #107: 
1. feature importance is unnecessary in a viz, now that it is output as an artifact
2. RFE and model parameters will be covered in a separate viz and separate PR

added scatterplot and confusion_matrix visualizers

---

q2_sample_classifier/assets/index.html
q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/utilities.py
q2_sample_classifier/visuals.py

summarizes estimator parameters and feature extraction results
the second half of #107 (other half is in #111, I decided to split the original viz into two)

new visualizer: `summarize`

---

q2_sample_classifier/__init__.py
q2_sample_classifier/_type.py
q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/utilities.py
q2_sample_classifier/visuals.py

accuracy viz input validation and support for mismatched true/predicted labels

---

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py

rename predict methods

---

README.md

updating readme to 2018.8

---

q2_sample_classifier/classify.py
q2_sample_classifier/tests/test_classifier.py

fixed stratification error

---

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py

Added a new heatmap pipeline for creating abundance heatmaps of important features.
Eventually this will go into the main pipelines (e.g., `classify_samples`) but for now will leave it out for a release

heatmap pipeline

---

q2_sample_classifier/plugin_setup.py

heatmap metadata description had some copypasta. Now fixed.

fixed heatmap metadata description

---

q2_sample_classifier/_transformer.py
q2_sample_classifier/tests/data/categorical_predictions.tsv
q2_sample_classifier/tests/test_classifier.py

adjusted transformers to ensure numeric transformation of importance + prediction results

---

q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/utilities.py
q2_sample_classifier/visuals.py

fix binary ROC bug

---

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_classifier.py

blocked by https://github.com/qiime2/q2-feature-table/pull/216

annotate heatmaps with feature metadata

---

q2_sample_classifier/visuals.py

note cividis maps to cividis_r to go from light to dark

added cividis colormap

---

q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py

Closes #161, is this along the lines of what you want @nbokulich? I literally just have the `classify-samples` and `regress-samples` returning a heatmap along with there other returns.

IMP: Add heatmap to pipelines

---

LICENSE
q2_sample_classifier/__init__.py
q2_sample_classifier/_format.py
q2_sample_classifier/_transformer.py
q2_sample_classifier/_type.py
q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/__init__.py
q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/utilities.py
q2_sample_classifier/visuals.py
setup.py

Updated copyright headers to reflect current year.

MAINT: Updated copyright header to 2020

---

q2_sample_classifier/classify.py
q2_sample_classifier/tests/test_classifier.py
q2_sample_classifier/tests/test_estimators.py

While working on #194 I noticed a bunch of weird little linting errors. This cleans those up.

MAINT: Lotta weird linting errors

---

q2_sample_classifier/assets/index.html
q2_sample_classifier/tests/test_actions.py

also, minor copyediting in `summarize` visualization
Pair-programmed with @Keegan-Evans.
---
@Jiung-Wen - do you have minute or two to look at some new unit tests we would like to add, related to your recent RFE TSV contribution in #199? Thanks!

tst: adding unit tests for rfe tsv outputs

---

q2_sample_classifier/assets/index.html
q2_sample_classifier/classify.py
q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_estimators.py
q2_sample_classifier/utilities.py

closes #205 allowing model training on complete dataset (`test_size=0.0`)

ENH: added option to train on complete dataset

---

q2_sample_classifier/plugin_setup.py
q2_sample_classifier/tests/test_estimators.py
q2_sample_classifier/utilities.py

Closes #2.
- `ExtraTree` implemented
- test cases and parameters adapted accordingly

FEAT other base estimators for `AdaBoost`
