- setup.py
When installing with pip (without `-e`), running visualizers fails without this package data.
> BUG: adds missing package data

- q2_sample_classifier/visuals.py
that was easy.
The yticklabels are now right-aligned, as shown below (the nonsensical labels were added in for the sake of ensuring that this worked with very long labels):
fixes #44
> fixed yticklabel horizontal alignment

- q2_sample_classifier/classify.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/utilities.py
- q2_sample_classifier/visuals.py
the default is nice and soft... but many of the matplotlib defaults don't look great for this. I added a number of choices for palettes that seem okay, but it may make more sense at some point to define custom seaborn color palettes (how about this: each member of the qiime2 dev team gets to define their own color palette and then we can have "Greg's theme", etc)
The issue is that the confusion matrices tend to include mostly zero values and a handful of values close to 1 (ideally), with few intermediate values. For many [default colormaps](https://matplotlib.org/examples/color/colormaps_reference.html), this yields a bold color on a (nearly) white background, which is a bit hard on the eyes.
fixes #43
> added color palette selection and nice default color scheme

- README.md
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/visuals.py
fixes #49 
Here is an example confusion matrix table. what do you think @gregcaporaso ?
> baseline error, ratio, and description in readme

- q2_sample_classifier/visuals.py
Requires `seaborn 0.8` to function correctly. 
Fixes #50.
> BUG: fix sorting issue in heatmap

- q2_sample_classifier/tests/test_classifier.py
This prevents transient issues which should be dealt with in another
way, but for now this avoids stochastic failure while testing.
> TST: adds random_state to visualizer tests

- q2_sample_classifier/classify.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/utilities.py
- q2_sample_classifier/visuals.py
Most of the default seaborn color schemes really don't work well for the classification confusion matrix heatmaps. The reason is that these heatmaps contain many values at the extremes and fewer intermediates values, and some colormaps have very bold colors, very dark colors, or black/white at both termini. With the wrong color palette, the results can make your eyes bleed.
So I made my own custom color palettes with softer termini and cheesier names.
Also added a unit test to verify that all color palette names are valid input for `sns.heatmap`.
> added new color palette schemes

- q2_sample_classifier/__init__.py
- q2_sample_classifier/_format.py
- q2_sample_classifier/_type.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/tests/data/outliers.tsv
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/utilities.py
Fixes #103 
The changes in this PR represent my review of the changes merged as part of #100/#101.
---
- Removed errant `assert`
- Cleaned up circular imports
- Revised new formats
- Added some tests
> MAINT: Minor cleanup from recent changes

- q2_sample_classifier/classify.py
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/utilities.py
fixes #105 
fixes #114 
I added a test for the `split_table` action itself, but it should be unnecessary — the function tests now specifically test a `biom.Table` output — before the output was `pd.DataFrame` and then list of dicts, so there was ambiguity that allowed #114 to slip by undetected. Let me know if I should drop that.
> split on metadata, fix split_table bug

- q2_sample_classifier/_format.py
- q2_sample_classifier/_transformer.py
- q2_sample_classifier/citations.bib
- q2_sample_classifier/classify.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/utilities.py
fixes #84 
depends on #115 #113 #111 
the old visualizers have been replaced and are no longer registered; the underlying functions still exist (renamed *_samples_basic) and will be cleaned out in a separate PR (since several other functions will need to be purged along with them). _These are resulting in a large drop in coverage but just ignore that._
the pipelines have the same names and deliver the same results (see unit tests; the test procedures have changed, but the same expected results are used).
> classify-samples and regress-samples vizs are replaced with pipelines

- q2_sample_classifier/tests/test_classifier.py
just threw in an extra test to make sure that feature order does not impact `predict`.
We had a similar test that got bulldozed with the changes in #101 due to substantial functionality changes
> test predict works on shuffled features

- q2_sample_classifier/tests/test_classifier.py
Fixes a PR-mania-induced test misordering issue
[build 211](https://travis-ci.org/qiime2/q2-sample-classifier/builds/405031264) failed because #121 inserted a new test in test class `EstimatorsTests`. However, #115 (merged recently, but only after #121 was issued) inserted a new test class ahead of that position, causing this new test to be bumped into the new test class (without raising a merge conflict).
> fixed test order

- paper/references.bib
this presumably was the cause of reference formatting inconsistency in the pdf preview.
> joss paper: fixed reference name inconsistency

- q2_sample_classifier/classify.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/tests/test_classifier.py
fixes #85 
This is a temporary fix. This method does not operate on negative values, which could be potentially important. Positive numeric still covers most use cases, so I think it is worth considering this method.
> metatable method: convert/merge metadata into feature table

- ci/recipe/meta.yaml
- q2_sample_classifier/_transformer.py
- q2_sample_classifier/tests/test_classifier.py
sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23, so adding joblib as a dependency.
IGNORE THE TRAVIS FAILURES, THIS IS DUE TO AN UNRELATED ISSUE (🐼 problems?)
> added joblib dependency

- q2_sample_classifier/tests/test_classifier.py
_extract_rfe_scores suddenly started failing in the dev build. It appears that the failure was due to the small size of the test data (not sure what changed in sklearn but `rfecv.grid_scores_` were failing to compute, returning an array of `NaN`s)
So I just increased the length of the test data and all appears to be working swell. (this change of course requires new expected scores as well) 
**Update re: commit 2**: For some reason travis is getting slightly different test results than I am locally (macOS Mojave 10.14.5). I changed test precision to 1 decimal, but perhaps we should be concerned about mac and linux delivering different results?
> fixed _extract_rfe_scores tests with new test dataset

- q2_sample_classifier/classify.py
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/utilities.py
Heading off various warnings not already fixed by #152 and #151 
Travis will fail: these are the 6 tests fixed in #152 
NOTE: SVM estimators were updated to use `gamma=scale` by default (in advance of future changes to that default). This does change prediction results, as reflected in the diff. No other changes altered the expected test results.
> fixed some DeprecationWarning and other warnings, updated SVMs

- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/visuals.py
fixes #171 
grabs classes from the probabilities, instead of from the predictions. this fixes the bug that causes roc to error when predictions are missing some classes (this will only occur with very small sample sizes or very large class counts without stratification).
added a test to make sure everything's peachy when predictions are missing classes that are in probabilities.
> roc missing class test

- q2_sample_classifier/classify.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/utilities.py
- q2_sample_classifier/visuals.py
Closes #148 Adds ability to adjust colorscale of heatmaps derived from confusion matrices via seaborn's vmin and vmax parameters. Is this along the lines of what you want @nbokulich? Once the parameters are properly implemented I can add some tests.
> IMP: Add ability to adjust heatmap colorscale

- q2_sample_classifier/_transformer.py
- q2_sample_classifier/tests/test_classifier.py
Pandas has deprecated the from_csv method in favor of read_csv as of v0.21.0. This change is needed to make plugins pass unit tests utilizing the newest version of pandas v0.25.1. Fixes issue #176
> MAINT: removed use of deprecated method from_csv

- q2_sample_classifier/classify.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/tests/test_classifier.py
fixes #173 
While fixing #173 (adding drop_all_unique param), I also discovered that dropping negative values was acting on the wrong axis. It had not been detected by unit tests previously because the `drop_all_unique` was dropping the negative values in the test data already. I fixed the code and tweaked two tests to ensure that 1) negative filtering and 2) `drop_all_unique` are working as intended.
> added drop_all_unique param

- ci/recipe/meta.yaml
This pin it to help determine issues for the current build prior to the release.
> Pin scikit-learn to same version as feature-classifier

- .gitignore
- q2_sample_classifier/visuals.py
closes #143 , supersedes https://github.com/qiime2/q2-sample-classifier/pull/180
Thanks, @danteese for helping kick this off! Hopefully, this PR finishes what you started. :slightly_smiling_face: 
Thanks @Oddant1 for wallowing in the matplotlib docs with me.
These changes allow `heatmap` to render a heatmap of an arbitrary number of classes, displaying all classes as labels, preserving a 1:1 aspect for heatmap cells, and resizing the plot dynamically to accommodate. 
---
**Questions:** 
1. Cell size - Is this a good size for the boxes/cells that make up the heatmap itself? Do they need upsizing or downsizing? Screencaps attached below, at tiny, medium, and very large.
2. Borders - We don't outline many of our plots. I assume we want to stick with that here? I've mocked an outlined one as …
> BUG: heatmap now displays all classes properly, resizes dynamically

- q2_sample_classifier/assets/index.html
- q2_sample_classifier/utilities.py
Fixes #184 
Generate a RFE scores file (accuracy and feature count) and create a link to download it.
> ENH: `summarize` should provide link to download raw data from RFE plots

- q2_sample_classifier/classify.py
- q2_sample_classifier/plugin_setup.py
- q2_sample_classifier/tests/test_classifier.py
- q2_sample_classifier/tests/test_estimators.py
This PR rewrites slightly the `classify_samples_from_dist` to:
- introduce cross-validation
- replace the custom KNN implementation with the sklearn one for consistency.
The final confusion matrix is generated by collecting test samples from all the folds and comparing those to the ground truth.
> ENH: add cross-validation to KNN with DistanceMatrix
